version: '3.9'
services:
  frontend:
    build: ./front-end
    container_name: app_frontend
    ports:
      - 3000:3000
    platform: linux/x86_64 
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}